=== LetteVerein/archivator/Integrationstest/testplan.xsd
<?xml version="1.0" encoding="UTF-8"?>
<xs:schema id="testplan" targetNamespace="http://www.archivator.de/testplan"
	xmlns:tns="http://www.archivator.de/testplan" xmlns="http://www.archivator.de/testplan"
	xmlns:xs="http://www.w3.org/2001/XMLSchema" attributeFormDefault="unqualified"
	elementFormDefault="qualified" >
	<xs:element name="testplan">
		<xs:complexType>
			<xs:sequence minOccurs="1" maxOccurs="unbounded">
				<xs:element name="testfall">
					<xs:complexType>
						<xs:sequence>
							<xs:element name="vorraussetzungen" minOccurs="1"
								maxOccurs="unbounded">
								<xs:complexType>
									<xs:sequence>
										<xs:element name="vorraussetzung" minOccurs="1"
											maxOccurs="unbounded" type="xs:string">
										</xs:element>
									</xs:sequence>
								</xs:complexType>
							</xs:element>
							<xs:element name="durchfÃ¼hrung" minOccurs="1"
								maxOccurs="unbounded">
								<xs:complexType>
									<xs:sequence>
										<xs:element name="schritt">
											<xs:complexType mixed="true">
												<xs:sequence>
													<xs:element name="ergebnisse" minOccurs="1"
														maxOccurs="unbounded">
														<xs:complexType>
															<xs:sequence>
																<xs:element name="ergebnis" minOccurs="1"
																	maxOccurs="unbounded" type="xs:string">
																</xs:element>
															</xs:sequence>
														</xs:complexType>
													</xs:element>
												</xs:sequence>
											</xs:complexType>
										</xs:element>
									</xs:sequence>
								</xs:complexType>
							</xs:element>
						</xs:sequence>
						<xs:attribute name="titel" type="xs:string" use="required" />
						<xs:anyAttribute/>
					</xs:complexType>
				</xs:element>
			</xs:sequence>
		</xs:complexType>
	</xs:element>
</xs:schema>

=== LetteVerein/archivator/Integrationstest/testplan.xml
<?xml version="1.0" encoding="UTF-8"?>
<testplan xmlns="http://www.archivator.de/testplan" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
	xsi:schemaLocation="http://www.archivator.de/testplan testplan.xsd">
	<testfall titel="test">
		<vorraussetzungen>
			<vorraussetzung></vorraussetzung>
		</vorraussetzungen>
		<durchführung>
			<schritt>
				<ergebnisse>
					<ergebnis />
				</ergebnisse>
			</schritt>
		</durchführung>
	</testfall>
</testplan>

=== LetteVerein/archivator/Integrationstest/BearbeitungBlockierenTest.xml
<?xml version="1.0" encoding="UTF-8"?>
<testplan xmlns="http://www.archivator.de/testplan" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
	xsi:schemaLocation="http://www.archivator.de/testplan testplan.xsd">
	<testfall titel="Bearbeitung verwehren">
		<vorraussetzungen>
			<vorraussetzung>Benutzer ist nicht angemeldet.</vorraussetzung>
		</vorraussetzungen>
		<durchführung>
			<schritt>
			    <!-- Benutzer öffnet ein Archivale zur Detailansicht. -->
				<ergebnisse>
					<ergebnis><!-- Kein Bearbeitungsbutton wird angezeigt. --></ergebnis>
				</ergebnisse>
			</schritt>
		</durchführung>
		<durchführung>
		    <schritt>
			    <!-- Falls der Bearbeitungsbutton angezeigt wird, wird dieser Schritt ausgeführt. -->
			    <!-- Bearbeiten-Button wird ausgewählt. -->
			    <ergebnisse>
			        <ergebnis><!-- Dem Benutzer wird über ein Textfeld mitgeteilt, dass er 
			            keine Zugriffsrechte hat. --></ergebnis>
			    </ergebnisse>
			</schritt>
		</durchführung>
	</testfall>
</testplan>
